### ISSUE TITLE
Get videos does not work

### ISSUE THREAD

**Issue by manguon** [RobertGrubb/tiktok-php#10] opened 2020-06-20 20:54 UTC
Hi, @RobertGrubb 

I use: **$scraper->user->videos('iratee', 10);**

But it return:  **Array ( [error] => 1 [message] => Status code 0 was returned )**

How to fix it?

Thanks

**Comment by RobertGrubb** [comment] 2020-06-20 23:18
Will look into this, im currently not getting this issue during my tests, but will look into testing it on multiple hosts. If I can manage to hit the same bug, ill look into solutions.

**Comment by manguon** [comment] 2020-06-21 02:34
The error appears when I run on PHP 7.4

On PHP 7.2, it worked fine.

How to fix on PHP 7.4?

**Comment by RobertGrubb** [comment] 2020-06-21 17:06
Very interesting! I'll look into what part of the syntax is breaking for 7.4. Thanks for the info!

**Comment by manguon** [comment] 2020-06-22 15:50
Any updates?

**Comment by RobertGrubb** [comment] 2020-07-07 08:30
I apologize this has taken so long, it's on my todo list today to see what the issue is with 7.4. Thanks again for pointing this out.

**Comment by RobertGrubb** [comment] 2020-07-20 22:01
Pushing updates for this in the next release (which is tomorrow). Once again, thank you for finding this bug.

**Comment by RobertGrubb** [comment] 2020-07-21 15:26
Hey there!

I have thoroughly reviewed this issue, and have installed the following version of php, and it seems to run just fine:

```
php -v
PHP 7.4.8 (cli) (built: Jul  9 2020 23:43:51) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.8, Copyright (c), by Zend Technologies
```

Using the following: 

```
use TikTok\Scraper;
$scraper = new Scraper();

try {
  $data = $scraper->user->videos('iratee', 10);
  if ($scraper->error) print_r($scraper->error);
  print_r($data);
} catch (Exception $e) {
  echo $e->getMessage() . PHP_EOL;
}
```

Which outputs:

```
stdClass Object
(
    [statusCode] => 0
    [items] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 6821468282583928069
                    [desc] => This song has been stuck in my head. Remember, enjoy life, and don't get hung up on the stuff that isn't important. ❤ #fun #singing #fyp #foryoupage
                    [createTime] => 1588246852
                    [video] => stdClass Object
                        (
                            [id] => awesome
                            [height] => 1024
                            [width] => 576
                            [duration] => 15
                            [ratio] => 720p
```

Can you should me the script that you're running with php `7.4`? Wondering if it's possibly an extension issue with PHP itself on your machine?

**Comment by RobertGrubb** [comment] 2020-07-21 15:36
I'm going to close this for now, but feel free to reopen if you find any more information on this.

**Closed as completed by RobertGrubb** 2020-07-21 15:36 UTC
Labels: bug, next-release
